### ISSUE TITLE
CRUD jugador

### ISSUE THREAD

**Issue by andres174** [andres174/project-p5-sports-backend#4]
CRUD jugador

**Comment by bermeo2000** [comment]
Terminado controlador
![image](https://user-images.githubusercontent.com/104100468/227727336-1526272e-f015-4264-b1e9-f63c6a5b4902.png)
![image](https://user-images.githubusercontent.com/104100468/227727383-e49331d0-65a0-4ddf-98fa-9d621e4ea386.png)
![image](https://user-images.githubusercontent.com/104100468/227727405-93850f49-db7e-44ac-a1c3-bd96049b1b27.png)
![image](https://user-images.githubusercontent.com/104100468/227727437-86ff60a4-1404-4b6a-8d4a-1ea767ec6707.png)
![image](https://user-images.githubusercontent.com/104100468/227727461-6ada298c-a994-4426-a86b-68155dbc1b0b.png)
![image](https://user-images.githubusercontent.com/104100468/227727501-ab775d4c-afa9-4b4a-8e24-6e8f305a2416.png)


Terminada las Api
![image](https://user-images.githubusercontent.com/104100468/227727252-d4448da7-f843-433a-a6e3-7f863b7d3aa1.png)

**Comment by bermeo2000** [comment]
Controladores
![image](https://user-images.githubusercontent.com/104100468/228073066-57c63b90-cb5b-486f-becb-f2cf26669c9b.png)
![image](https://user-images.githubusercontent.com/104100468/228073341-8844c924-d387-4aeb-80ff-e41eae85a25b.png)
![image](https://user-images.githubusercontent.com/104100468/228073471-6b482748-c4be-4037-81c8-ef8a10d0ab19.png)
![image](https://user-images.githubusercontent.com/104100468/228073561-a2e62d7b-9efc-4974-a548-4bf16aa05156.png)
![image](https://user-images.githubusercontent.com/104100468/228073667-7c5a8a06-c88b-402d-8a58-85382947ded6.png)
![image](https://user-images.githubusercontent.com/104100468/228073744-01ae2cbd-55b5-44a7-b6c9-cd5f0309d421.png)
